python run_pretrainfin.py \
--mixed_precision bf16 \
--task_name long_term_forecast \
--is_training 1 \
--root_path ../FNSPID_dataset/fin/ \
--model_id LLM4FN_50_3 \
--model TimeLLM \
--llm_model GPT2 \
--llm_dim 768 \
--llm_layers 12 \
--data fin \
--features M \
--factor 3 \
--enc_in 7 \
--dec_in 7 \
--c_out 7 \
--des 'Exp'\
--itr 1\
--d_model 32 \
--d_ff 128 \
--llm_layers 6 \
--train_epochs 100 \
--model_comment 'TimeLLM-LLM4FN' \
--target 'Close' \
--lradj 'type4' \
--batch_size 1